language: ruby
rvm:
  - 2.1.2

addons:
  postgresql: "9.1"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - DB=postgresql

bundler_args: --without development production --deployment
cache: bundler

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec